### ISSUE TITLE
Add a "Deploy to Heroku" badge to the README

### ISSUE THREAD

**Issue by raisedhand** [aahnik/telewater#8]
hi Aahnik ,
please if it's possible make deploy to heroku button for free of monthly vps charge. also heroku have any buildpack you need like selenium , chrome headless , ffmpeg , or ...
waiting for your response
finest regards

**Comment by aahnik** [comment]
I have started hating Heroku, for many reasons.

they seduce you with a free trial but is not good for commercial use.

deploying to Heroku has some other hassles also. 

but as there is public demand, I will definitely add it.

**Comment by aahnik** [comment]
hi @raisedhand, your request is fulfilled.

Check out the update telewater. It is ready to be deployed to Heroku.
